version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment: 
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  express-server:
    build: 
      dockerfile: Dockerfile.dev
      context: ./express-server
    volumes: 
      - /app/node_modules
      - ./express-server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
        - /app/node_modules
        - ./client:/app
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
        - /app/node_modules
        - ./worker:/app
  nginx:
    depends_on:
      - express-server
      - client
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
        
